name: Selenium POM Parallel Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]
        headless: [true]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Run tests with Maven (${{ matrix.browser }} headless=${{ matrix.headless }})
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: ${{ matrix.headless }}
        run: mvn clean test -Dbrowser=${{ matrix.browser }} -Dheadless=${{ matrix.headless }}

      - name: Upload Report Folder (ExtentReport + Screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Report-${{ matrix.browser }}
          path: target/report